version: '3.1'
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: Test123*
    ports:
      - 27017:27017  
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: AdminME
      ME_CONFIG_BASICAUTH_PASSWORD: METest123*
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: Test123*
      ME_CONFIG_MONGODB_URL: mongodb://admin:Test123*@mongo:27017/